development:
  dialect: postgres
  database: back2_school_development
  user: postgres
  password: postgres
  host: db
  pool: 5

test:
  dialect: postgres
  database: back2_school_test
  user: postgres
  password: postgres
  host: db
  pool: 5

production:
  dialect: postgres
  database: back2_school_production
  user: postgres
  password: postgres
  host: db
  pool: 5
