[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "v0.13.0-beta.2"

[prune]
  go-tests = true
  unused-packages = true


  # DO NOT DELETE
  [[prune.project]] # buffalo
    name = "github.com/gobuffalo/buffalo"
    unused-packages = false

  # DO NOT DELETE
  [[prune.project]] # pop
    name = "github.com/gobuffalo/pop"
    unused-packages = false
