version: '2'

tasks:
  run-db:
    cmds:
      - sudo docker run -d --rm --name back2school-db -e POSTGRES_PASSWORD=postgres --network host postgres
      - echo 'Wait some time to make sure that the db is properly initialized and is accepting connections'

  stop-db:
    cmds:
      - sudo docker stop back2school-db

  init-db:
    cmds:
      - buffalo pop create
      - buffalo pop migrate
      - buffalo task db:seed

  reset-db:
    cmds:
      - buffalo pop reset
      - buffalo pop migrate
      - buffalo task db:seed

  psql:
    cmds:
      - sudo docker run --rm -it --network host -e COLUMNS="$(tput cols)" -e LINES="$(tput lines)" postgres psql -h localhost -U postgres
