package actions

import (
	"fmt"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/middleware2018-PSS/back2_school/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Account)
// DB Table: Plural (accounts)
// Resource: Plural (Accounts)
// Path: Plural (/accounts)
// View Template Folder: Plural (/templates/accounts/)

// AccountsResource is the resource for the Account model
type AccountsResource struct {
	buffalo.Resource
}

// List gets all Accounts. This function is mapped to the path
// GET /accounts
// @Tags Accounts
// @Summary List accounts
// @Description get accounts
// @Accept  json
// @Produce  json
// @Security ApiKeyAuth
// @Param q query string false "name search by q"
// @Success 200 {array} models.Account
// @Failure 400 {object} models.HTTPError
// @Failure 404 {object} models.HTTPError
// @Failure 500 {object} models.HTTPError
// @Router /accounts [get]
func (v AccountsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}
	fmt.Println(c.Value("contentType").(string))
	accounts := &models.Accounts{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Accounts from the DB
	if err := q.All(accounts); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, accounts))
}

// Show gets the data for one Account. This function is mapped to
// the path GET /accounts/{account_id}
func (v AccountsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Account
	account := &models.Account{}

	// To find the Account the parameter account_id is used.
	if err := tx.Find(account, c.Param("account_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, account))
}

// New renders the form for creating a new Account.
// This function is mapped to the path GET /accounts/new
func (v AccountsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Account{}))
}

// Create adds a Account to the DB. This function is mapped to the
// path POST /accounts
func (v AccountsResource) Create(c buffalo.Context) error {
	// Allocate an empty Account
	account := &models.Account{}

	// Bind account to the html form elements
	if err := c.Bind(account); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(account)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, account))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Account was created successfully")

	// and redirect to the accounts index page
	return c.Render(201, r.Auto(c, account))
}

// Edit renders a edit form for a Account. This function is
// mapped to the path GET /accounts/{account_id}/edit
func (v AccountsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Account
	account := &models.Account{}

	if err := tx.Find(account, c.Param("account_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, account))
}

// Update changes a Account in the DB. This function is mapped to
// the path PUT /accounts/{account_id}
func (v AccountsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Account
	account := &models.Account{}

	if err := tx.Find(account, c.Param("account_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Account to the html form elements
	if err := c.Bind(account); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(account)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, account))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Account was updated successfully")

	// and redirect to the accounts index page
	return c.Render(200, r.Auto(c, account))
}

// Destroy deletes a Account from the DB. This function is mapped
// to the path DELETE /accounts/{account_id}
func (v AccountsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Account
	account := &models.Account{}

	// To find the Account the parameter account_id is used.
	if err := tx.Find(account, c.Param("account_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(account); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Account was destroyed successfully")

	// Redirect to the accounts index page
	return c.Render(200, r.Auto(c, account))
}
