package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/middleware2018-PSS/back2_school/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Appointment)
// DB Table: Plural (appointments)
// Resource: Plural (Appointments)
// Path: Plural (/appointments)
// View Template Folder: Plural (/templates/appointments/)

// AppointmentsResource is the resource for the Appointment model
type AppointmentsResource struct {
	buffalo.Resource
}

// List gets all Appointments. This function is mapped to the path
// GET /appointments
func (v AppointmentsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	appointments := &models.Appointments{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Appointments from the DB
	if err := q.All(appointments); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, appointments))
}

// Show gets the data for one Appointment. This function is mapped to
// the path GET /appointments/{appointment_id}
func (v AppointmentsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Appointment
	appointment := &models.Appointment{}

	// To find the Appointment the parameter appointment_id is used.
	if err := tx.Find(appointment, c.Param("appointment_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, appointment))
}

// New renders the form for creating a new Appointment.
// This function is mapped to the path GET /appointments/new
func (v AppointmentsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Appointment{}))
}

// Create adds a Appointment to the DB. This function is mapped to the
// path POST /appointments
func (v AppointmentsResource) Create(c buffalo.Context) error {
	// Allocate an empty Appointment
	appointment := &models.Appointment{}

	// Bind appointment to the html form elements
	if err := c.Bind(appointment); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(appointment)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, appointment))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Appointment was created successfully")

	// and redirect to the appointments index page
	return c.Render(201, r.Auto(c, appointment))
}

// Edit renders a edit form for a Appointment. This function is
// mapped to the path GET /appointments/{appointment_id}/edit
func (v AppointmentsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Appointment
	appointment := &models.Appointment{}

	if err := tx.Find(appointment, c.Param("appointment_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, appointment))
}

// Update changes a Appointment in the DB. This function is mapped to
// the path PUT /appointments/{appointment_id}
func (v AppointmentsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Appointment
	appointment := &models.Appointment{}

	if err := tx.Find(appointment, c.Param("appointment_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Appointment to the html form elements
	if err := c.Bind(appointment); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(appointment)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, appointment))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Appointment was updated successfully")

	// and redirect to the appointments index page
	return c.Render(200, r.Auto(c, appointment))
}

// Destroy deletes a Appointment from the DB. This function is mapped
// to the path DELETE /appointments/{appointment_id}
func (v AppointmentsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Appointment
	appointment := &models.Appointment{}

	// To find the Appointment the parameter appointment_id is used.
	if err := tx.Find(appointment, c.Param("appointment_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(appointment); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Appointment was destroyed successfully")

	// Redirect to the appointments index page
	return c.Render(200, r.Auto(c, appointment))
}
