package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/middleware2018-PSS/back2_school/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Grade)
// DB Table: Plural (grades)
// Resource: Plural (Grades)
// Path: Plural (/grades)
// View Template Folder: Plural (/templates/grades/)

// GradesResource is the resource for the Grade model
type GradesResource struct {
	buffalo.Resource
}

// List gets all Grades. This function is mapped to the path
// GET /grades
func (v GradesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	grades := &models.Grades{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Grades from the DB
	if err := q.All(grades); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, grades))
}

// Show gets the data for one Grade. This function is mapped to
// the path GET /grades/{grade_id}
func (v GradesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Grade
	grade := &models.Grade{}

	// To find the Grade the parameter grade_id is used.
	if err := tx.Find(grade, c.Param("grade_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, grade))
}

// New renders the form for creating a new Grade.
// This function is mapped to the path GET /grades/new
func (v GradesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Grade{}))
}

// Create adds a Grade to the DB. This function is mapped to the
// path POST /grades
func (v GradesResource) Create(c buffalo.Context) error {
	// Allocate an empty Grade
	grade := &models.Grade{}

	// Bind grade to the html form elements
	if err := c.Bind(grade); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(grade)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, grade))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Grade was created successfully")

	// and redirect to the grades index page
	return c.Render(201, r.Auto(c, grade))
}

// Edit renders a edit form for a Grade. This function is
// mapped to the path GET /grades/{grade_id}/edit
func (v GradesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Grade
	grade := &models.Grade{}

	if err := tx.Find(grade, c.Param("grade_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, grade))
}

// Update changes a Grade in the DB. This function is mapped to
// the path PUT /grades/{grade_id}
func (v GradesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Grade
	grade := &models.Grade{}

	if err := tx.Find(grade, c.Param("grade_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Grade to the html form elements
	if err := c.Bind(grade); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(grade)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, grade))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Grade was updated successfully")

	// and redirect to the grades index page
	return c.Render(200, r.Auto(c, grade))
}

// Destroy deletes a Grade from the DB. This function is mapped
// to the path DELETE /grades/{grade_id}
func (v GradesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Grade
	grade := &models.Grade{}

	// To find the Grade the parameter grade_id is used.
	if err := tx.Find(grade, c.Param("grade_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(grade); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Grade was destroyed successfully")

	// Redirect to the grades index page
	return c.Render(200, r.Auto(c, grade))
}
