package actions

import (
	"bytes"
	"net/http"

	"github.com/cippaciong/jsonapi"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/middleware2018-PSS/back2_school/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Notification)
// DB Table: Plural (notifications)
// Resource: Plural (Notifications)
// Path: Plural (/notifications)
// View Template Folder: Plural (/templates/notifications/)

// NotificationsResource is the resource for the Notification model
type NotificationsResource struct {
	buffalo.Resource
}

// List gets all Notifications. This function is mapped to the path
// GET /notifications
// @Summary List notifications
// @Description Get the list of all notifications
// @Tags Notifications
// @Accept  json
// @Produce  json
// @Success 200 {array} models.Notification
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /notifications [get]
// @Security ApiKeyAuth
func (v NotificationsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "No transaction found", "Internal Server Error",
			http.StatusInternalServerError, errors.New("No transaction found"))
	}

	notifications := &models.Notifications{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Notifications from the DB
	if err := q.All(notifications); err != nil {
		return apiError(c, "Internal Error", "Internal Server Error",
			http.StatusInternalServerError, err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	res := new(bytes.Buffer)
	err := jsonapi.MarshalPayload(res, *notifications)
	if err != nil {
		log.Debug("Problem marshalling notifications in actions.NotificationsResource.List")
		return apiError(c, "Internal Error preparing the response payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	return c.Render(200, r.Func("application/json",
		customJSONRenderer(res.String())))
}

// Show gets the data for one Notification. This function is mapped to
// the path GET /notifications/{notification_id}
// @Summary Get a notification
// @Description Get a single notification and its relationships
// @Tags Notifications
// @Accept  json
// @Produce  json
// @Success 200 {object} models.Notification
// @Failure 404 {object} jsonapi.ErrorObject
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /notifications/{id} [get]
// @Security ApiKeyAuth
func (v NotificationsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "No transaction found", "Internal Server Error",
			http.StatusInternalServerError, errors.New("No transaction found"))
	}

	// Allocate an empty Notification
	notification := &models.Notification{}

	// To find the Notification the parameter notification_id is used.
	if err := tx.Eager().Find(notification, c.Param("notification_id")); err != nil {
		return apiError(c, "The requested resource cannot be found",
			"Not Found", http.StatusNotFound, err)
	}

	// Remove user passwords from the response
	for _, user := range notification.Users {
		(*user).Password = ""
	}

	res := new(bytes.Buffer)
	err := jsonapi.MarshalPayload(res, notification)
	if err != nil {
		return apiError(c, "Internal Error preparing the response payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	return c.Render(200, r.Func("application/json",
		customJSONRenderer(res.String())))
}

// New renders the form for creating a new Notification.
// This function is mapped to the path GET /notifications/new
func (v NotificationsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Notification{}))
}

// Create adds a Notification to the DB. This function is mapped to the
// path POST /notifications
// @Summary Create a notification
// @Description Create a notification from the payload
// @Tags Notifications
// @Accept  json
// @Produce  json
// @Param Notification body models.Notification true "Notification payload"
// @Success 200 {object} models.Notification
// @Failure 404 {object} jsonapi.ErrorObject
// @Failure 422 {object} jsonapi.ErrorObject
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /notifications [post]
// @Security ApiKeyAuth
func (v NotificationsResource) Create(c buffalo.Context) error {
	// Allocate an empty Notification
	notification := &models.Notification{}

	// Unmarshal notification from the json payload
	if err := jsonapi.UnmarshalPayload(c.Request().Body, notification); err != nil {
		return apiError(c, "Error processing the request payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "Internal error", "Internal Server Error",
			http.StatusInternalServerError, errors.New("no transaction found"))
	}

	// Create and save the notification
	verrs, err := tx.ValidateAndCreate(notification)
	if err != nil {
		return apiError(c, "Validation Error", "Unprocessable Entity",
			http.StatusUnprocessableEntity, err)
	}

	// Check for validation errors
	if verrs.HasAny() {
		return apiError(c, "Validation Error", "Unprocessable Entity",
			http.StatusUnprocessableEntity, verrs)
	}

	// Log notification creation
	log.Debug("Notification created in actions.NotificationsResource.Create:\n%v\n", notification)

	// Reload the notification to rebuild relationships
	if err := tx.Eager().Find(notification, notification.ID); err != nil {
		return apiError(c, "The requested resource cannot be found",
			"Not Found", http.StatusNotFound, err)
	}

	// Remove user passwords from the response
	for _, user := range notification.Users {
		(*user).Password = ""
	}

	// If there are no errors return the Notification resource
	res := new(bytes.Buffer)
	err = jsonapi.MarshalPayload(res, notification)
	if err != nil {
		return apiError(c, "Error processing the response payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}
	return c.Render(200, r.Func("application/json",
		customJSONRenderer(res.String())))
}

// Edit renders a edit form for a Notification. This function is
// mapped to the path GET /notifications/{notification_id}/edit
func (v NotificationsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Notification
	notification := &models.Notification{}

	if err := tx.Find(notification, c.Param("notification_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, notification))
}

// Update changes a Notification in the DB. This function is mapped to
// the path PUT /notifications/{notification_id}
// @Summary Update a notification
// @Description Update a notification from the payload
// @Tags Notifications
// @Accept  json
// @Produce  json
// @Param Notification body models.Notification true "Notification payload"
// @Success 200 {object} models.Notification
// @Failure 404 {object} jsonapi.ErrorObject
// @Failure 422 {object} jsonapi.ErrorObject
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /notifications [put]
// @Security ApiKeyAuth
func (v NotificationsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "Internal error", "Internal Server Error",
			http.StatusInternalServerError, errors.New("no transaction found"))
	}

	// Allocate an empty Notification
	notification := &models.Notification{}

	if err := tx.Find(notification, c.Param("notification_id")); err != nil {
		return apiError(c, "Cannot update the resource. Resource not found",
			"Not Found", http.StatusNotFound, err)
	}

	// Unmarshall the JSON payload into a Notification struct
	if err := jsonapi.UnmarshalPayload(c.Request().Body, notification); err != nil {
		return apiError(c, "Error processing the request payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	// Update the notification in the DB
	verrs, err := tx.ValidateAndUpdate(notification)
	if err != nil {
		return apiError(c, "Internal error",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	// Check for validation errors
	if verrs.HasAny() {
		return apiError(c, "Validation Error", "Unprocessable Entity",
			http.StatusUnprocessableEntity, verrs)
	}

	// Reload the notification to rebuild relationships
	if err := tx.Eager().Find(notification, notification.ID); err != nil {
		return apiError(c, "The requested resource cannot be found",
			"Not Found", http.StatusNotFound, err)
	}

	// Remove user passwords from the response
	for _, user := range notification.Users {
		(*user).Password = ""
	}

	// Marshal the resource and send it back
	res := new(bytes.Buffer)
	err = jsonapi.MarshalPayload(res, notification)
	if err != nil {
		return apiError(c, "Internal Error preparing the response payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	return c.Render(200, r.Func("application/json",
		customJSONRenderer(res.String())))
}

// Destroy deletes a Notification from the DB. This function is mapped
// to the path DELETE /notifications/{notification_id}
// @Summary Delete a notification
// @Description Delete a notification
// @Tags Notifications
// @Accept  json
// @Produce  json
// @Param  id path int true "Notification ID" Format(uuid)
// @Success 204 {object} models.Notification
// @Failure 404 {object} jsonapi.ErrorObject
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /notifications/{id} [delete]
// @Security ApiKeyAuth
func (v NotificationsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "Internal error", "Internal Server Error",
			http.StatusInternalServerError, errors.New("no transaction found"))
	}

	// Allocate an empty Notification
	notification := &models.Notification{}

	// To find the Notification the parameter notification_id is used.
	if err := tx.Find(notification, c.Param("notification_id")); err != nil {
		return apiError(c, "Cannot delete resource. Resource not found",
			"Not Found", http.StatusNotFound, err)
	}

	if err := tx.Destroy(notification); err != nil {
		return apiError(c, "Internal error", "Internal Server Error",
			http.StatusInternalServerError, err)
	}

	// Redirect to the notifications index page
	return c.Render(204, r.Func("application/json",
		customJSONRenderer("")))
}
