package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/middleware2018-PSS/back2_school/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Notification)
// DB Table: Plural (notifications)
// Resource: Plural (Notifications)
// Path: Plural (/notifications)
// View Template Folder: Plural (/templates/notifications/)

// NotificationsResource is the resource for the Notification model
type NotificationsResource struct {
	buffalo.Resource
}

// List gets all Notifications. This function is mapped to the path
// GET /notifications
func (v NotificationsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	notifications := &models.Notifications{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Notifications from the DB
	if err := q.All(notifications); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, notifications))
}

// Show gets the data for one Notification. This function is mapped to
// the path GET /notifications/{notification_id}
func (v NotificationsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Notification
	notification := &models.Notification{}

	// To find the Notification the parameter notification_id is used.
	if err := tx.Find(notification, c.Param("notification_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, notification))
}

// New renders the form for creating a new Notification.
// This function is mapped to the path GET /notifications/new
func (v NotificationsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Notification{}))
}

// Create adds a Notification to the DB. This function is mapped to the
// path POST /notifications
func (v NotificationsResource) Create(c buffalo.Context) error {
	// Allocate an empty Notification
	notification := &models.Notification{}

	// Bind notification to the html form elements
	if err := c.Bind(notification); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(notification)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, notification))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Notification was created successfully")

	// and redirect to the notifications index page
	return c.Render(201, r.Auto(c, notification))
}

// Edit renders a edit form for a Notification. This function is
// mapped to the path GET /notifications/{notification_id}/edit
func (v NotificationsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Notification
	notification := &models.Notification{}

	if err := tx.Find(notification, c.Param("notification_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, notification))
}

// Update changes a Notification in the DB. This function is mapped to
// the path PUT /notifications/{notification_id}
func (v NotificationsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Notification
	notification := &models.Notification{}

	if err := tx.Find(notification, c.Param("notification_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Notification to the html form elements
	if err := c.Bind(notification); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(notification)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, notification))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Notification was updated successfully")

	// and redirect to the notifications index page
	return c.Render(200, r.Auto(c, notification))
}

// Destroy deletes a Notification from the DB. This function is mapped
// to the path DELETE /notifications/{notification_id}
func (v NotificationsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Notification
	notification := &models.Notification{}

	// To find the Notification the parameter notification_id is used.
	if err := tx.Find(notification, c.Param("notification_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(notification); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Notification was destroyed successfully")

	// Redirect to the notifications index page
	return c.Render(200, r.Auto(c, notification))
}
