package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/middleware2018-PSS/back2_school/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Payment)
// DB Table: Plural (payments)
// Resource: Plural (Payments)
// Path: Plural (/payments)
// View Template Folder: Plural (/templates/payments/)

// PaymentsResource is the resource for the Payment model
type PaymentsResource struct {
	buffalo.Resource
}

// List gets all Payments. This function is mapped to the path
// GET /payments
func (v PaymentsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	payments := &models.Payments{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Payments from the DB
	if err := q.All(payments); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, payments))
}

// Show gets the data for one Payment. This function is mapped to
// the path GET /payments/{payment_id}
func (v PaymentsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Payment
	payment := &models.Payment{}

	// To find the Payment the parameter payment_id is used.
	if err := tx.Find(payment, c.Param("payment_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, payment))
}

// New renders the form for creating a new Payment.
// This function is mapped to the path GET /payments/new
func (v PaymentsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Payment{}))
}

// Create adds a Payment to the DB. This function is mapped to the
// path POST /payments
func (v PaymentsResource) Create(c buffalo.Context) error {
	// Allocate an empty Payment
	payment := &models.Payment{}

	// Bind payment to the html form elements
	if err := c.Bind(payment); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(payment)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, payment))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Payment was created successfully")

	// and redirect to the payments index page
	return c.Render(201, r.Auto(c, payment))
}

// Edit renders a edit form for a Payment. This function is
// mapped to the path GET /payments/{payment_id}/edit
func (v PaymentsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Payment
	payment := &models.Payment{}

	if err := tx.Find(payment, c.Param("payment_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, payment))
}

// Update changes a Payment in the DB. This function is mapped to
// the path PUT /payments/{payment_id}
func (v PaymentsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Payment
	payment := &models.Payment{}

	if err := tx.Find(payment, c.Param("payment_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Payment to the html form elements
	if err := c.Bind(payment); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(payment)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, payment))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Payment was updated successfully")

	// and redirect to the payments index page
	return c.Render(200, r.Auto(c, payment))
}

// Destroy deletes a Payment from the DB. This function is mapped
// to the path DELETE /payments/{payment_id}
func (v PaymentsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Payment
	payment := &models.Payment{}

	// To find the Payment the parameter payment_id is used.
	if err := tx.Find(payment, c.Param("payment_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(payment); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Payment was destroyed successfully")

	// Redirect to the payments index page
	return c.Render(200, r.Auto(c, payment))
}
