package actions

import (
	"bytes"
	"net/http"

	"github.com/cippaciong/jsonapi"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/middleware2018-PSS/back2_school/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Student)
// DB Table: Plural (students)
// Resource: Plural (Students)
// Path: Plural (/students)
// View Template Folder: Plural (/templates/students/)

// StudentsResource is the resource for the Student model
type StudentsResource struct {
	buffalo.Resource
}

// List gets all Students. This function is mapped to the path
// GET /students
// @Summary List students
// @Description Get the list of all students
// @Tags Students
// @Accept  json
// @Produce  json
// @Success 200 {array} models.Student
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /students [get]
func (v StudentsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "No transaction found", "Internal Server Error",
			http.StatusInternalServerError, errors.New("No transaction found"))
	}

	students := &models.Students{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Students from the DB
	if err := q.All(students); err != nil {
		return apiError(c, "Internal Error", "Internal Server Error",
			http.StatusInternalServerError, err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	res := new(bytes.Buffer)
	err := jsonapi.MarshalPayload(res, *students)
	if err != nil {
		log.Debug("Problem marshalling students in actions.StudentsResource.List")
		return apiError(c, "Internal Error preparing the response payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	return c.Render(200, r.Func("application/json",
		customJSONRenderer(res.String())))
}

// Show gets the data for one Student. This function is mapped to
// the path GET /students/{student_id}
// @Summary Get a student
// @Description Get a single student and its relationships
// @Tags Students
// @Accept  json
// @Produce  json
// @Success 200 {object} models.Student
// @Failure 404 {object} jsonapi.ErrorObject
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /students/{id} [get]
func (v StudentsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "No transaction found", "Internal Server Error",
			http.StatusInternalServerError, errors.New("No transaction found"))
	}

	// Allocate an empty Student
	student := &models.Student{}

	// To find the Student the parameter student_id is used.
	if err := tx.Eager("Parents").Find(student, c.Param("student_id")); err != nil {
		return apiError(c, "The requested resource cannot be found",
			"Not Found", http.StatusNotFound, err)
	}

	res := new(bytes.Buffer)
	err := jsonapi.MarshalPayload(res, student)
	if err != nil {
		return apiError(c, "Internal Error preparing the response payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	return c.Render(200, r.Func("application/json",
		customJSONRenderer(res.String())))
}

// New renders the form for creating a new Student.
// This function is mapped to the path GET /students/new
func (v StudentsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Student{}))
}

// Create adds a Student to the DB. This function is mapped to the
// path POST /students
// @Summary Create a student
// @Description Create a student from the payload
// @Tags Students
// @Accept  json
// @Produce  json
// @Param Student body models.Student true "Student payload"
// @Success 200 {object} models.Student
// @Failure 404 {object} jsonapi.ErrorObject
// @Failure 422 {object} jsonapi.ErrorObject
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /students [post]
func (v StudentsResource) Create(c buffalo.Context) error {
	// Allocate an empty Student
	student := &models.Student{}
	if err := jsonapi.UnmarshalPayload(c.Request().Body, student); err != nil {
		return apiError(c, "Error processing the request payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "Internal error", "Internal Server Error",
			http.StatusInternalServerError, errors.New("no transaction found"))
	}

	// Create and save the student
	verrs, err := tx.ValidateAndCreate(student)
	if err != nil {
		return apiError(c, "Validation Error", "Unprocessable Entity",
			http.StatusUnprocessableEntity, err)
	}

	// Check for validation errors
	if verrs.HasAny() {
		return apiError(c, "Validation Error", "Unprocessable Entity",
			http.StatusUnprocessableEntity, verrs)
	}

	// Log student creation
	log.Debug("Student created in actions.StudentsResource.Create:\n%v\n", student)

	// Reload the student with proper parent information
	if err := tx.Eager("Parents").Find(student, student.ID); err != nil {
		return apiError(c, "The requested resource cannot be found",
			"Not Found", http.StatusNotFound, err)
	}

	// If there are no errors return the Student resource
	res := new(bytes.Buffer)
	err = jsonapi.MarshalPayload(res, student)
	if err != nil {
		return apiError(c, "Error processing the response payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}
	return c.Render(200, r.Func("application/json",
		customJSONRenderer(res.String())))
}

// Edit renders a edit form for a Student. This function is
// mapped to the path GET /students/{student_id}/edit
func (v StudentsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Student
	student := &models.Student{}

	if err := tx.Find(student, c.Param("student_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, student))
}

// Update changes a Student in the DB. This function is mapped to
// the path PUT /students/{student_id}
// @Summary Update a student
// @Description Update a student from the payload
// @Tags Students
// @Accept  json
// @Produce  json
// @Param Student body models.Student true "Student payload"
// @Success 200 {object} models.Student
// @Failure 404 {object} jsonapi.ErrorObject
// @Failure 422 {object} jsonapi.ErrorObject
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /students [put]
func (v StudentsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "Internal error", "Internal Server Error",
			http.StatusInternalServerError, errors.New("no transaction found"))
	}

	// Allocate an empty Student
	student := &models.Student{}

	if err := tx.Find(student, c.Param("student_id")); err != nil {
		return apiError(c, "Cannot update the resource. Resource not found",
			"Not Found", http.StatusNotFound, err)
	}

	// Unmarshall the JSON payload into a Student struct
	if err := jsonapi.UnmarshalPayload(c.Request().Body, student); err != nil {
		return apiError(c, "Error processing the request payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	// Update the student in the DB
	verrs, err := tx.ValidateAndUpdate(student)
	if err != nil {
		return apiError(c, "Internal error",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	// Check for validation errors
	if verrs.HasAny() {
		return apiError(c, "Validation Error", "Unprocessable Entity",
			http.StatusUnprocessableEntity, verrs)
	}

	// Reload the student with proper parent information
	if err := tx.Eager().Find(student, student.ID); err != nil {
		return apiError(c, "The requested resource cannot be found",
			"Not Found", http.StatusNotFound, err)
	}

	// Marshal the resource and send it back
	res := new(bytes.Buffer)
	err = jsonapi.MarshalPayload(res, student)
	if err != nil {
		return apiError(c, "Internal Error preparing the response payload",
			"Internal Server Error", http.StatusInternalServerError, err)
	}

	return c.Render(200, r.Func("application/json",
		customJSONRenderer(res.String())))
}

// Destroy deletes a Student from the DB. This function is mapped
// to the path DELETE /students/{student_id}
// @Summary Delete a student
// @Description Delete a student
// @Tags Students
// @Accept  json
// @Produce  json
// @Param  id path int true "Student ID" Format(uuid)
// @Success 204 {object} models.Student
// @Failure 404 {object} jsonapi.ErrorObject
// @Failure 500 {object} jsonapi.ErrorObject
// @Router /students/{id} [delete]
func (v StudentsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return apiError(c, "Internal error", "Internal Server Error",
			http.StatusInternalServerError, errors.New("no transaction found"))
	}

	// Allocate an empty Student
	student := &models.Student{}

	// To find the Student the parameter student_id is used.
	if err := tx.Find(student, c.Param("student_id")); err != nil {
		return apiError(c, "Cannot delete resource. Resource not found",
			"Not Found", http.StatusNotFound, err)
	}

	if err := tx.Destroy(student); err != nil {
		return apiError(c, "Internal error", "Internal Server Error",
			http.StatusInternalServerError, err)
	}

	// Redirect to the students index page
	return c.Render(204, r.Func("application/json",
		customJSONRenderer("")))
}
