package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/middleware2018-PSS/back2_school/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Teacher)
// DB Table: Plural (teachers)
// Resource: Plural (Teachers)
// Path: Plural (/teachers)
// View Template Folder: Plural (/templates/teachers/)

// TeachersResource is the resource for the Teacher model
type TeachersResource struct {
	buffalo.Resource
}

// List gets all Teachers. This function is mapped to the path
// GET /teachers
func (v TeachersResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	teachers := &models.Teachers{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Teachers from the DB
	if err := q.All(teachers); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, teachers))
}

// Show gets the data for one Teacher. This function is mapped to
// the path GET /teachers/{teacher_id}
func (v TeachersResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Teacher
	teacher := &models.Teacher{}

	// To find the Teacher the parameter teacher_id is used.
	if err := tx.Find(teacher, c.Param("teacher_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, teacher))
}

// New renders the form for creating a new Teacher.
// This function is mapped to the path GET /teachers/new
func (v TeachersResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Teacher{}))
}

// Create adds a Teacher to the DB. This function is mapped to the
// path POST /teachers
func (v TeachersResource) Create(c buffalo.Context) error {
	// Allocate an empty Teacher
	teacher := &models.Teacher{}

	// Bind teacher to the html form elements
	if err := c.Bind(teacher); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(teacher)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, teacher))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Teacher was created successfully")

	// and redirect to the teachers index page
	return c.Render(201, r.Auto(c, teacher))
}

// Edit renders a edit form for a Teacher. This function is
// mapped to the path GET /teachers/{teacher_id}/edit
func (v TeachersResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Teacher
	teacher := &models.Teacher{}

	if err := tx.Find(teacher, c.Param("teacher_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, teacher))
}

// Update changes a Teacher in the DB. This function is mapped to
// the path PUT /teachers/{teacher_id}
func (v TeachersResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Teacher
	teacher := &models.Teacher{}

	if err := tx.Find(teacher, c.Param("teacher_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Teacher to the html form elements
	if err := c.Bind(teacher); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(teacher)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, teacher))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Teacher was updated successfully")

	// and redirect to the teachers index page
	return c.Render(200, r.Auto(c, teacher))
}

// Destroy deletes a Teacher from the DB. This function is mapped
// to the path DELETE /teachers/{teacher_id}
func (v TeachersResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Teacher
	teacher := &models.Teacher{}

	// To find the Teacher the parameter teacher_id is used.
	if err := tx.Find(teacher, c.Param("teacher_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(teacher); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Teacher was destroyed successfully")

	// Redirect to the teachers index page
	return c.Render(200, r.Auto(c, teacher))
}
